spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-blog

#spring_profiles_active:prod
##PROD_DB_HOST=containers-us-west-32.railway.app
##PROD_DB_PORT=6425
##PROD_DB_NAME=railway
##PROD_DB_PASSWORD=ATiMAk1lvg3vHPfcdB6C
##PROD_DB_USERNAME=postgres